name: Update Master Feed

on:
  schedule:
    - cron: "0 * * * *"  # Runs at minute 0 of every hour
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-master-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install GitHub CLI (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Download Release Asset using GitHub CLI
        run: |
          gh release download ${{ github.event.release.tag_name || 'latest' }} --pattern "rss_aggregator" --dir .
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Make Asset Executable
        run: chmod +x rss_aggregator

      - name: Run Release Binary to Generate master_feed.xml
        run: ./rss_aggregator

      - name: Commit changes if master_feed.xml updated
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain master_feed.xml)" ]; then
            git add master_feed.xml
            git commit -m "Update master feed [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes in master_feed.xml, skipping commit."
          fi
